#pragma once

#include <cstdint>



#define ERR_STR(e) ((char*) Err::str[-e])
#define ERR_PSTR(e) ((char**) &(Err::str[-e]))

namespace Err {

    enum Err : int64_t {
        OK                              = 0,
        MALLOC                          = -1,
        UNEXPECTED_END_OF_FILE          = -2,
        UNEXPECTED_END_OF_EXPRESSION    = -3,
        INVALID_OPERATOR                = -4,
        VARIABLE_ALREADY_DEFINED        = -5,
        FUNCTION_ALREADY_DEFINED        = -6,
        UNEXPECTED_SYMBOL               = -7,
        UNKNOWN_VARIABLE                = -8,
        UNKNOWN_FUNCTION                = -9,
        INVALID_NUMBER_LITERAL          = -10,
        INVALID_TYPE_CONVERSION         = -11,
        MISSING_VARIABLE_NAME           = -12,
        INVALID_TYPE_UNARY_OPERATOR     = -13,
        INVALID_TYPE_BINARY_OPERATOR    = -14,
        CANNOT_ASSIGN_TO_CONST          = -15,
        UNKNOWN_DATA_TYPE               = -16,
        INVALID_DATA_TYPE               = -17,
        COMPILE_TIME_KNOWN_EXPRESSION_REQUIRED = -18,
        TYPE_INIT_ATTRIBUTES_COUNT_MISMATCH    = -19,
        INVALID_ATTRIBUTE_NAME          = -20,
        OPERATOR_CANNOT_ACT_AS_UNARY    = -21,
        OPERATOR_CANNOT_ACT_AS_BINARY   = -22,
        CANNOT_GET_ADDRESS_OF_ADDRESS   = -23,
        INVALID_USAGE_OF_OPERATOR       = -24,
        CANNOT_EVALUATE_EXPRESION_AT_CMP_TIME = -25, // LOOK AT : maybe rename as NOT_COMPILE_TIME_EXPRESSION to make it shorter
        INVALID_EMBED_ARRAY_SIZE        = -26,
        UNKNOWN_QUALIFIER               = -27,
        ARRAY_EXPECTED                  = -28,
        TOO_MANY_ARGUMENTS              = -29,
        APPROPRIATE_TAG_DOES_NOT_EXISTS   = -30,
        BUFFER_OVERRUN                  = -31,
        SYSTEM_COMMAND_EXECUTION_FAILED    = -32,
        INVALID_LVALUE                  = -33,
        INVALID_VARIABLE_NAME           = -34,
        NOT_ENOUGH_ARGUMENTS            = -35,
        INVALID_DECLARATION_PLACE       = -36,
        UNKNOWN_NAMESPACE               = -37,
        INVALID_NUMBER_OF_ATTRIBUTES    = -38,
        UNSUPPORTED_ESCAPE_SEQUENCE     = -39,
        DATA_TYPE_SIZE_EXCEEDED         = -40,
        UNEXPECTED_ERROR                = -41,
        ARRAY_SIZE_MISMATCH             = -42,
        NO_MATCHING_FUNCTION_FOUND      = -43,
        MORE_THAN_ONE_OVERLOAD_MATCH    = -44,
        UNEXPECTED_RVALUE               = -45,
        UNKNOWN_ERROR_SET               = -46,
        INVALID_RVALUE                  = -47,
        SYMBOL_ALREADY_DEFINED          = -48,
        TCC_ERROR                       = -49,
        UNTERMINATED_COMMENT            = -50,
        INVALID_ARRAY_LENGTH            = -51,
        GLOBAL_SCOPE_REQUIRED           = -52,
        INVALID_DECLARATION_ORDER       = -53,
        CIRCULAR_IMPORT                 = -54,
        FILE_DOES_NOT_EXISTS            = -55,
        UNKNOWN_DIRECTIVE               = -56,
        INVALID_ARGUMENTS               = -57,
        NOT_YET_IMPLEMENTED             = -58,
        IO_ERROR                        = -59,
        MAX_FILE_PATH_EXCEEDED          = -60,
    };

    const char* const str[] = {

        "OK",
        "Malloc doesn't feel good...",
        "Unexpected end of file!",
        "Unexpected end of expression!",
        "Invalid operator '%.*s'!",
        "Variable '%.*s' already defined!",
        "Function already defined!",
        "Unexpected symbol! %s expected.",
        "Unknown variable '%.*s'!",
        "Unknown function '%.*s'!",
        "Invalid number literal!",
        "Type conversion between '%s' and '%s' types is invalid!",
        "Variable name is missing!",
        "Invalid type '%s' to unary operator '%s'!",
        "Invalid type '%s' to binary operator '%s'!",
        "Cannot assign to constant lvalue!",
        "Unknown data type!",
        "Invalid data type!",
        "Compile time known expression required!",
        "Attributes count mismatch! %i instead of %i given!",
        "Invalid attribute name '%.*s'!",
        "Operator '%.*s' cannot act as unary!",
        "Operator '%.*s' cannot act as binary!",
        "Cannot get address of address!",
        "Invalid usage of operator '%.*s'!",
        "Cannot evaluate expresion at compile time!",
        "Embed array requires compile time size!",
        "Unknown qualifier! Valid are 'const' or 'embed'",
        "Array expected!",
        "Too many arguments!",
        "Appropriate tag '%.*s' does not exists!",
        "Buffer overrun!",
        "System command execution failed!",
        "Invalid lvalue!",
        "Invalid variable name! '%.*s'",
        "Not enough input arguments in function call!",
        "%s is declared in invalid place!",
        "Unknown namespace!",
        "Invalid number of attributes.",
        "Unsupported escape sequence!",
        "Data type size exceeded!",
        "Unexpected error!",
        "Array size mismatch!",
        "No matching function found!",
        "More than one overload variant match the function call!",
        "Unexpected rvalue!",
        "Unknown error set!",
        "Invalid rvalue!",
        "Symbol already defined!",
        "TCC error!",
        "Unterminated comment!",
        "Invalid array length!",
        "Declaration requires global scope!",
        "Type definition '%.*s' includes type that is defined later! Move its definition before this one! Or may be you meant to use pointer?",
        "Circular import detected!",
        "File '%s' does not exists!",
        "Unknown directive!",
        "Invalid arguments!",
        "Not yet implemented!",
        "IO error!",
        "Max file path exceeded!"
    };

}
